---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2016

suites:
  - name: default
    run_list:
      - recipe[rdp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
#        - name: windows-baseline
#          git: https://github.com/dev-sec/windows-baseline.git
    attributes:
